lane :prepare_android do
end

lane :build_android do
  # Tell xcode to use the provisioning provile we provide to build the app
  build_android_app(
    task: "assemble",
    build_type: "Release",
    project_dir: "platforms/android/",
    properties: {
      "versionCode" => ENV["BUILD_NUMBER"],
      "versionName" => ENV["APP_VERSION"],
      "android.injected.signing.store.file" => ENV["KEYSTORE_FILE"],
      "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
      "android.injected.signing.key.alias" => ENV["SIGNING_KEY_ALIAS"],
      "android.injected.signing.key.password" => ENV["SIGNING_KEY_PASSWORD"]
    }
  )
end

lane :upload_android do
  upload_to_play_store(
    json_key: ENV["GOOGLE_PLAY_SERVICE_ACCOUNT"],
    # If you'd like to build multiple apps with identical settings, you could set this to an environment variable
    package_name: "de.fiveminds.deploydemo"
    apk: "platforms/android//app/build/outputs/apk/release/app-release.apk",
    track: "alpha"
  )
end
